### ISSUE TITLE
Add support for projects structure

### ISSUE THREAD

**Issue by ChristianKohler** [briebug/jest-schematic#11]
**Is your feature request related to a problem? Please describe.**
We have the following folder structure generated with the cli using this commands:

```
ng new jesttest2 --create-application=false --style=css --routing=false --directory=./

ng generate application jesttest2 --style=css  
```
When we then run the schematics it sets the root path to 'src'

**Describe the solution you'd like**
Add jest config to project

**Describe alternatives you've considered**
Do it manually

**Additional context**
Folderstructure after schematic:add

![Screenshot 2019-05-15 at 11 55 36](https://user-images.githubusercontent.com/4374178/57766883-73ef0a00-7708-11e9-8575-03224a90e1a7.png)

**Comment by schuchard** [comment]
Hi @ChristianKohler, unfortunately this is expected. Currently this schematic doesn't account for the possibility of multiple projects/applications or libraries. This will need to be a future improvement that relies on the angular.json mappings to add correct Jest setup. We'll keep this issue open as a reminder. Thanks for reporting.

**Comment by schuchard** [comment]
Please see if `ng add @briebug/jest-schematic@3.0.0-0` solves the issue

**Comment by ChristianKohler** [comment]
Yes it works 👍 Thank you @schuchard
