### ISSUE TITLE
Validation Error: Preset jest-preset-angular not found.

### ISSUE THREAD

**Issue by thogrego** [briebug/jest-schematic#111]
**Describe the bug**
After running the command "ng add @briebug/jest-schematic" inside of my angular app and then running "ng test", I receive an error:

Validation Error:

  Preset jest-preset-angular not found.

  Configuration Documentation:
  https://jestjs.io/docs/configuration

**To Reproduce**
1. Create a new ng app via CLI
2. Navigate to new app folder via CLI
3. execute CLI command "ng add @briebug/jest-schematic"
4. execute CLI command "ng test"

**Expected behavior**
I expected the 3 default unit tests in my app.component.spec.ts to pass successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/7985989/172404442-35fed5e1-94d5-429d-b37e-425be0d356f3.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Node version: v16.13.0
- App type: Angular CLI
- Angular version: 13.3.7

**Additional context**

**Comment by Waterstraal** [comment]
I have this exact same issue, using angular 14.2.1

Have you been able to work around this?

**Comment by Waterstraal** [comment]
To get it working, I did the following:

`npm install -D jest jest-preset-angular`

in `setup-jest.ts`:
change `import 'jest-preset-angular/setup-jest';` to `import 'jest-preset-angular';`

**Comment by Waterstraal** [comment]
I still see some issues in `test-config.helper.ts`. Since Angular 14.2 `TestBed.configureCompiler` returns a void instead of  `TestBedStatic`.

![image](https://user-images.githubusercontent.com/2691730/189305004-f359fd62-677b-4a9f-8378-1c9c3c603bc7.png)

**Comment by Waterstraal** [comment]
When I delete `test-config.helper.ts`, everything still seems to run fine. Is this file still needed for something?

**Comment by DasOhmoff** [comment]
I also have this same issue with the `test-config.helper.ts` file. How can this be fixed? Just deleting the file seems a little risky for me. @schuchard What is the current status of this and how can this be fixed?

**Comment by schuchard** [comment]
Can you test with [latest v5.0.0](https://github.com/briebug/jest-schematic/releases/tag/v5.0.0) and let me know if that helps? `test-config.helper.ts` has been removed.
