### ISSUE TITLE
Issue with Angular 8: `src/tsconfig.spec.json` => `tsconfig.spec.json`

### ISSUE THREAD

**Issue by yjaaidi** [briebug/jest-schematic#12]
**Describe the bug**
Using the schematic with Angular 8 then running the tests will produce the following error:
```
 File not found: <rootDir>/src/tsconfig.spec.json (resolved as: /.../src/tsconfig.spec.json)
```

This is due to the fact that Angular 8 moves `tsconfig.spec.json` out of `src` while `jest-angular-preset` is expecting `tsconfig.spec.json` to be in `src`.

Maybe `jest-angular-preset` should automatically detect `tsconfig.spec.json` location but it might be easier to handle this in this schematic as a temporary fix.

Meanwhile, there are two workarounds (and maybe more):
1. 😔Move `tsconfig.spec.json` back to `src`.
2. ✅Update `jest.config.js`:
```js
const tsJestPreset = require('jest-preset-angular/jest-preset').globals['ts-jest'];

module.exports = {
  ...
  globals: {
    'ts-jest': {
      ...tsJestPreset,
      tsConfig: 'tsconfig.spec.json'
    }
  }
};
```

**To Reproduce**
1. npm install -g @angular/cli@8.0.0
2. ng add @briebug/jest-schematic
3. npm test

**Comment by schuchard** [comment]
Thanks for putting this through an early Angular 8 test and for investigating the issue and resolutions.

**Comment by yjaaidi** [comment]
Thank you for the schematic 😊

**Comment by itayod** [comment]
@yjaaidi I took a look into it and I think it's an issue in `jest-preset-angular`

**Comment by yjaaidi** [comment]
I just opened the issue on **jest-preset-angular** too https://github.com/thymikee/jest-preset-angular/issues/286

**Comment by quincarter** [comment]
Also getting this same issue in an angular 8 project.

**Comment by ceciliazcx** [comment]
Also getting this same issue in an angular 8 project. +1

**Comment by aijazkhan81** [comment]
+1 On Ng7
