### ISSUE TITLE
Running `ng add @briebug/jest-schematic` on an Angular 15 project throws error 

### ISSUE THREAD

**Issue by Waterstraal** [briebug/jest-schematic#127]
**Describe the bug**

**To Reproduce**

1. `npx @angular/cli@15 new angular-with-jest-test`
2. `cd .\angular-with-jest-test\`
3. `ng add @briebug/jest-schematic`
4. The following error is thrown: `Cannot read properties of undefined (reading 'filter')`

**Expected behavior**
Jest is configured for an Angular 15 project

**Screenshots**
![image](https://user-images.githubusercontent.com/2691730/202689013-c6b699d4-b228-418f-ba82-f17cfc9c894a.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Node version: 18.12.1
- App type: Angular cli
- Angular version: 15

**Comment by schuchard** [comment]
#128 should fix the issue. However, deployment is blocked by https://github.com/sindresorhus/np/pull/666

**Comment by a1development** [comment]
is there any workaround to get this running on my end?

**Comment by schuchard** [comment]
https://github.com/briebug/jest-schematic/releases/tag/v6.0.0 adds support for Angular 15. Please reopen if you still have an issue with v6. Thanks.
