### ISSUE TITLE
Hangs on "add" to ng new project in Angular 8

### ISSUE THREAD

**Issue by brandonmerritt** [briebug/jest-schematic#13]
**Describe the bug**
When running the "add" schematic everything hangs.
Angular CLI: 8.0.4
Node: 10.15.3
OS: darwin x64
Angular: 8.0.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect              0.800.4
@angular-devkit/build-angular      0.800.4
@angular-devkit/build-optimizer   0.800.4
@angular-devkit/build-webpack    0.800.4
@angular-devkit/core                      8.0.4
@angular-devkit/schematics          8.0.4
@angular/cli                                      8.0.4
@ngtools/webpack                          8.0.4
@schematics/angular                      8.0.4
@schematics/update                       0.800.4
rxjs                                                     6.4.0
typescript                                         3.4.5
webpack                                           4.30.0

**To Reproduce**
Add to a new NG project
Watch it hang

**Expected behavior**
It's possible that "add" just takes a really long time and I'm not patient enough. If that's the case maybe I just need to request a "User Feedback" feature request.

**Additional context**
I originally used the NPM Module in a scaffolding script. Because it seems to hang it breaks my script. It would be helpful to add the ability to "break on error" to the module. Within the script I get no error feedback even if I'm not within an Angular project. If I try to run in directly (outside a project) I get an error. I don't necessarily think this is related, but the lack of error handling seems to cause problems for scripting.

**Comment by schuchard** [comment]
Hi @brandonmerritt, thanks for reporting. Please try out the [latest version](https://github.com/briebug/jest-schematic/releases/tag/v2.0.0) to see if you're still seeing an issue. 

This schematic installs the latest version of packages which relies on an internet connection [here](https://github.com/briebug/jest-schematic/blob/master/src/jest/index.ts#L69). There may be an opportunity to timeout this request and fallback to a static version in a future release if this is an issue. Let me know if 2.0.0 fixes your original issue.
