### ISSUE TITLE
Does not remove src/test.ts from tsconfig.spec.json

### ISSUE THREAD

**Issue by Halt001** [briebug/jest-schematic#15]
**Describe the bug**
After running `ng g @briebug/jest-schematic:add` there is still a reference to `src/test.ts` left in `tsconfig.spec.json`. (This is with ng8)

The reason is that your code does indeed remove `src/test.ts` but looks for `test.ts` (not `src/test.ts`) in the `tsconfig.spec.json` file.

I tried making a PR because that describes the problem and the possible fix the best but I couldn't figure out how to fix the then failing test in the sandbox.

**To Reproduce**
1. run `ng new my-ng8-app`
2. run `ng g @briebug/jest-schematic:add`
3. Observe  `tsconfig.spec.json` has still a reference to `src/test.ts`

**Expected behavior**
The removal of `src/test.ts` from `tsconfig.spec.json`

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: Mac
 - Node version: v10.16.0
 - NPM version: 6.9.0
 - App type Angular CLI
 - Angular version: "@angular/core": "~8.2.5"

**Comment by rgunczer** [comment]
same here, "src/test.ts", is still in "tsconfig.spec.json" after manually removing I still have issue running tests:

 FAIL  src/app/app.component.spec.ts
  ● Test suite failed to run

    File not found: <rootDir>/src/tsconfig.spec.json (resolved as: C:\flanker\angular\jestApp\src\tsconfig.spec.json)
