### ISSUE TITLE
Cannot read property 'architect' of undefined

### ISSUE THREAD

**Issue by praveeno** [briebug/jest-schematic#28]
**Describe the bug**
Skipping installation: Package already installed
Cannot read property 'architect' of undefined

**To Reproduce**
initially trying to install, not working

**Screenshots**
![image](https://user-images.githubusercontent.com/19618730/82116865-3f35e880-978a-11ea-9201-d35895598721.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18 
 - Node version: v12.16.1 
 - NPM version 6.13.4
 - App type - Angular CLI
 - Angular version - @angular/core: "9.1.3"

**Comment by assisgui** [comment]
I'm facing similar error, but the message is "Could not read package.json" after the installation with yarn:

![image](https://user-images.githubusercontent.com/13773375/91600218-fb807c80-e93d-11ea-96e9-2d8984dabe22.png)

**Comment by schuchard** [comment]
Are either of these projects public?

**Comment by assisgui** [comment]
No, sorry, my project is private :(

**Comment by schuchard** [comment]
Please see if `ng add @briebug/jest-schematic@3.0.0-0` solves the issue

**Comment by schuchard** [comment]
This should be fixed, please re-open if the issue exist in the latest release of 3.0.0
