### ISSUE TITLE
Make ng test work

### ISSUE THREAD

**Issue by mvollebregt** [briebug/jest-schematic#30]
**Is your feature request related to a problem? Please describe.**

This is an awesome schematic. It would be even more awesome, if you could run the jest specs by entering `ng test`. After adding the jest-schematic, ng test does not run the tests anymore.

**Describe the solution you'd like**

Make the jest-schematic:

- install @angular-builders/jest (`npm i -D jest @types/jest @angular-builders/jest`)
- in angular.json, replace `@angular-devkit/build-angular:karma` with `@angular-builders/jest:run`

**Comment by brianpooe** [comment]
@mvollebregt why wont you create a PR for this seems like you already know what the solution is, amd see if they agree with it for a merge.

**Comment by mvollebregt** [comment]
I had a short look at it before, but I had some trouble finding out how the schematics worked. I'll see if I have some more time later to dive into that. In the meanwhile, I just wanted to explain the improvement, in case someone happened to be able to fix it easily.

**Comment by schuchard** [comment]
Please try `ng add @briebug/jest-schematic@3.0.0-0` which adds this functionality
