### ISSUE TITLE
Running in an Angular 10 project fails

### ISSUE THREAD

**Issue by afluegge** [briebug/jest-schematic#32]
**Describe the bug**
It is not possible to replace Karma with Jest using this tool.

**To Reproduce**
1. Run 'ng add @briebug/jest-schematic'
2. See error

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/946209/87045737-84a9eb80-c1f8-11ea-80a2-908cb5a9616b.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Node version: [14.5.0]
 - NPM or Yarn version [6.14.5]
 - App type [Angular CLI]
 - Angular version [@angular/cli: "10.0.1"]

**Additional context**
None

**Comment by fireflysemantics** [comment]
Same here.

**Comment by JanGerritsen** [comment]
Same here.
Added Text of error message so this ticket can be easily found through searches:

> Cannot read property 'name' of undefined

**Comment by tevenFr** [comment]
same here
```    "@angular/animations": "~10.0.5",
    "@angular/common": "~10.0.5",
    "@angular/compiler": "~10.0.5",
    "@angular/core": "~10.0.5",
    "@angular/forms": "~10.0.5",
    "@angular/platform-browser": "~10.0.5",
    "@angular/platform-browser-dynamic": "~10.0.5",
    "@angular/router": "~10.0.5",
    "@briebug/cypress-schematic": "^3.3.0",
    "@briebug/jest-schematic": "^2.1.1",

**Comment by Unknown47Dream** [comment]
any progress on this?

**Comment by brianpooe** [comment]
+1

**Comment by Kexplx** [comment]
same

**Comment by schuchard** [comment]
Thanks for the report, I'm able to reproduce too. I'm starting to put time into updating this schematic so that it works with Angular 10.

**Comment by fireflysemantics** [comment]
@schuchard YOU ROCK!!  This schematic is awesome!!

**Comment by americoneto1** [comment]
@schuchard this PR fixes this issue? https://github.com/briebug/jest-schematic/pull/35

**Comment by brianpooe** [comment]
@americoneto1 Do you know when will your PR be merged?

**Comment by schuchard** [comment]
Hi everyone, version `2.2.0` has been published and should now work when running `ng add @briebug/jest-schematic` against Angular 10 projects. 

👏 A big thank you to Ludovic L'Hours (@madbrain) for adjusting the schematic to work with Angular 10 🎉
