### ISSUE TITLE
error: "Cannot set property 'builder' of undefined"

### ISSUE THREAD

**Issue by joeeames** [briebug/jest-schematic#42]
**Describe the bug**
When running either "ng add @briebug/jest-schematic" or "ng g @briebug/jest-schematic:add" the error "Cannot set property 'builder' of undefined" is given

**To Reproduce**
1. Go to https://github.com/joeeames/UnitTestingAngularLikeABoss/tree/jest-solution
2. clone, make sure you're on the jest-solution branch.
3. npm i
4. execute either of the two commands above
5. See error

**Expected behavior**
no error
![schematic-error](https://user-images.githubusercontent.com/1072285/95667239-594cda80-0b20-11eb-9c63-5b710f863965.png)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Mac & Windows]
 - Node version: [14.7.0]
 - NPM or Yarn version [npm 6.14.7]
 - App type [Angular CLI]
 - Angular version [10.1.5]

**Additional context**
This was discovered on a windows box, then verified on a separate Mac

**Comment by schuchard** [comment]
Thanks for reporting @joeeames, I'll investigate.

**Comment by schuchard** [comment]
I've updated the tests to check for your type of example, which was an angular.json project config without a test builder path. I tested against your repo and it ran successfully. Let me know if you still have an issue.
