### ISSUE TITLE
test replacing ts-jest with @swc-node/jest

### ISSUE THREAD

**Issue by sod** [briebug/jest-schematic#49]
We don't use this package, but we use jest & angular and maybe you are interested.

We replaced ts-jest with [@swc-node/jest](https://yarnpkg.com/package/@swc-node/jest). Cold cache `jest` went from 60s to 7s.

[swc](https://swc-project.github.io/) is a typescript to javascript compiler that also supports annotations & metadata export, thus works with angular jit. swc is written in rust and is ~70x faster as typescript. So by using it you eliminate the compile overhead and are mostly left running the tests themself.

using swc-jest as a jest transformer is pretty straight forward, this is our transform block in `jest.config.js`

```typescript
    transform: {
        '\\.ts$': [
            require.resolve('@swc-node/jest'),
            {
                target: 'es2018',
                module: 'commonjs',
                experimentalDecorators: true,
                emitDecoratorMetadata: true,
                dynamicImport: true,
                sourcemap: true,
            },
        ],
    }
```

**Comment by leo-amelyan** [comment]
@sod Is there an Angular project that is using @swc-node/jest? Could you provide a  link?

**Comment by rene-leanix** [comment]
@lamelyan, I stumbled upon @sod's [example repo](https://github.com/sod/angular-jest-swc) for this. It does not include Zone.js yet.

**Comment by sod** [comment]
I gonna close as won't do. I have no time right now to contribute a PR.
