### ISSUE TITLE
Deprecation warning, install issue

### ISSUE THREAD

**Issue by inorganik** [briebug/jest-schematic#6]
Great work on this! Finally testing it out. With current `jest.config.js` file:

`setupTestFrameworkScriptFile: '<rootDir>/src/setup-jest.ts',`

throws a deprecation warning: "Option "setupTestFrameworkScriptFile" was replaced by configuration "setupFilesAfterEnv", which supports multiple paths."

It should be replaced with:

`setupFilesAfterEnv: ['<rootDir>/src/setup-jest.ts'],`

I also noticed that I needed to install the schematic locally in the project before I could run it:

`npm i @briebug/jest-schematic -D`.

**Comment by anthonymjones** [comment]
I'll take a look at this.

**Comment by schuchard** [comment]
Thanks for reporting. Should be a simple change. 

Regarding install, did either of these install methods not work for you?
https://github.com/briebug/jest-schematic/blob/master/README.md#usage-

**Comment by schuchard** [comment]
fixed by #7
