### ISSUE TITLE
Cannot read property 'filter' of undefined error

### ISSUE THREAD

**Issue by gmaughan** [briebug/jest-schematic#75]
**Describe the bug**

Error thrown "Cannot read property 'filter' of undefined" when installing and running.

**To Reproduce**

I'm using the following command to execute:

```sh
npx ng add @briebug/jest-schematic
```

I do not have any packages installed globally.

Output is as follows:

```sh
ℹ Using package manager: npm
✔ Found compatible package version: @briebug/jest-schematic@3.1.0.
✔ Package information loaded.

The package @briebug/jest-schematic@3.1.0 will be installed and executed.
Would you like to proceed? Yes
✔ Package successfully installed.
"BriebugSchematicsJest" schema is using the keyword "id" which its support is deprecated. Use "$id" for schema ID.
Cannot read property 'filter' of undefined
```

Installation of the package succeeds. Running the add schematic with:

```sh 
npx ng g @briebug/jest-schematic:add
```

Results in:

```sh
"BriebugSchematicsJest" schema is using the keyword "id" which its support is deprecated. Use "$id" for schema ID.
Cannot read property 'filter' of undefined
```

**Expected behavior**

Not expecting any errors.

**Desktop (please complete the following information):**
 - OS: Windows
 - Node version: 14.17.5
 - NPM or Yarn version: npm 6.14.14
 - App type: Angular
 - Angular version: 12.2.8

**Comment by SchroederSteffen** [comment]
Hi,
Thanks for the v4 update @schuchard.
Unfortunately, at least for us, the error `Cannot read property 'filter' of undefined` still occurs with @briebug/jest-schematic v4 and Angular v13 (everything up-to-date).
Anyone else having the same issue?

**Comment by schuchard** [comment]
Are you still getting an error about the schema $id along with the filter error? 

I'm unable to reproduce with this schematics latest release and angular 13 on a mac. 
![Screen Shot 2021-12-15 at 1 27 41 PM](https://user-images.githubusercontent.com/10186449/146252099-77bcf5d8-b9dc-4731-9166-962bf42d0ca8.png)

**Comment by SchroederSteffen** [comment]
> Are you still getting an error about the schema $id along with the filter error?

No, that error is gone. 👍 

> I'm unable to reproduce with this schematics latest release and angular 13 on a mac.

I forgot to mention that it's an existing project that already had the latest v3 installed. I was hoping to re-execute the schematic to ensure everything is set up properly. For this, I had to delete the `setup-jest.ts` & `test-config.helper.ts` files. (I'm on Windows.)
We have a project for which the jest tests fail, while it works for another one that looks pretty much the same. That's why I was trying to re-apply your jest schematics.

Is this re-execution supposed to work?

**Comment by gfsd3v** [comment]
@schuchard  Thanks for the awesome work.

I'm also having the same error as @SchroederSteffen basically I upgraded my angular workspace v12 > v13 and jest stopped working, so I decided to delete everything related to jest, all the files, packages, caches, package/yarn.lock, etc and tried to execute the schematics again:

<details>
<summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/36668882/158183892-01dbea68-7bf9-433c-bae5-bd64f16e5646.png)
![image](https://user-images.githubusercontent.com/36668882/158184177-27b7119a-a40d-43bf-b4aa-b2c995ca4a7a.png)

</details>

**Comment by kklimczak** [comment]
I also tried to install 4.0 version on Angular 13 and I have the same problem. Thre project was bumped from v8.

**Comment by jmdjr** [comment]
brand new angular application,
$ npm --version
8.19.2
@angular-devkit/architect       0.1500.2
@angular-devkit/build-angular   15.0.2
@angular-devkit/core            15.0.2
@angular-devkit/schematics      15.0.2
@schematics/angular             15.0.2
rxjs                            7.5.7
typescript                      4.8.4

still getting 
Cannot read properties of undefined (reading 'filter')

**Comment by PaulDMooney** [comment]
I also run into this issue. Running this command to generate a brand new project:
```
npx -p @angular/cli@15 ng new sample-jest-application --style=scss
```

Then
```
cd sample-jest-application
```
Then
```
npm run ng add @briebug/jest-schematic 
```

I get the output
```
> sample-jest-application@0.0.0 ng
> ng "add" "@briebug/jest-schematic"

ℹ Using package manager: npm
✔ Found compatible package version: @briebug/jest-schematic@5.0.0.
✔ Package information loaded.

The package @briebug/jest-schematic@5.0.0 will be installed and executed.
Would you like to proceed? Yes
✔ Packages successfully installed.
Cannot read properties of undefined (reading 'filter')
```

npm version is `8.5.0`
node version is `v16.14.2`
OS: macOS 13.0 (22A380)
Processor: M1

**Comment by schuchard** [comment]
@PaulDMooney - I released version 6 today. Could you retry the commands again and see if the issue persists with version 6? It looks like your commands installed version 5. The [filter](https://github.com/briebug/jest-schematic/commit/0bca6877f49418603882632c80ef59a9ea3cab99#diff-25a66a7e37e960629b0190c269e91f2a60467766f89a2d2647caffddc26e1a2bL188) issues should be resolved now.

**Comment by PaulDMooney** [comment]
@schuchard - I have tried it with version 6 and it works. Good stuff!
