### ISSUE TITLE
Doesn't work with Angular 12.2 anymore

### ISSUE THREAD

**Issue by rainerhahnekamp** [briebug/jest-schematic#76]
**Describe the bug**
When I create a new Angular application and apply the schematics, the tests immediately fail.

```
Schema validation failed with the following errors:
Data path "/polyfills" must be array.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-cli-jest@0.0.0 test: `ng test`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-cli-jest@0.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```

**To Reproduce**
```bash
npx @angular/cli@12 new angular-cli-jest
npx ng add @briebug/jest-schematic
npm run test
```

**Desktop (please complete the following information):**
 - OS: Windows
 - Node version: 14.16.0
 - NPM or Yarn version: NPM 6.14.11
 - App type Angular CLI
 - Angular version 12.2

**Comment by spieIbug** [comment]
This problem is linked to angular.json validation
You can fix this by changing the test build configuration
`"polyfills": "src/polyfills.ts",` -> `"polyfills": ["src/polyfills.ts"],`
`"inlineStyleLanguage": "scss"`, -> `"inlineStyleLanguage": ["scss"],`
Here is the test config that should be generated
```
"test": {
    "builder": "@angular-builders/jest:run",
    "options": {
      "polyfills": ["src/polyfills.ts"],
      "tsConfig": "tsconfig.spec.json",
      "inlineStyleLanguage": ["scss"],
      "assets": [
        "src/favicon.ico",
        "src/assets"
      ],
      "styles": [
        "src/styles.scss"
      ],
      "scripts": []
    }
  }
```

**Comment by inorganik** [comment]
Could this be an issue with the [angular jest builder](https://www.npmjs.com/package/@angular-builders/jest)? Not sure where schema validation happens. I also had to change "assets" into an array of strings.

**Comment by patou** [comment]
I publish the correction on a new package npm :
https://www.npmjs.com/package/@patoudss/jest-schematic

Juste do :
```
ng add @patoudss/jest-schematic 
```
