### ISSUE TITLE
error TS6053: File '<app>/src/test.ts' not found.

### ISSUE THREAD

**Issue by dimpu** [briebug/jest-schematic#8]
**Describe the bug**

```
TypeScript diagnostics (customize using `[jest-config].globals.ts-jest.diagnostics` option):
   error TS6053: File '<app>/src/test.ts' not found.
```

**To Reproduce**
1) Create new angular app with angular-cli 
2) ng add @briebug/jest-schematic
3) npm run test

**Desktop (please complete the following information):**
 - OS: [Mac]
 - Node version: [v10.10.0]
 - NPM or Yarn version [npm 6]
 - App type [ Angular CLI]
 - Angular version [e.g. @angular/core: "7.2.0"]

**Comment by david-dasilva** [comment]
I had the same problem.
Resolved by modifying **src/tsconfig.spec.json** (see comment in file)
```{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/spec",
    "types": [
      "jasmine",
      "node"
    ],
    "module": "commonjs"
  },
  "files": [
    //"test.ts", // remove this line
    "polyfills.ts"
  ],
  "include": [
    "**/*.spec.ts",
    "**/*.d.ts"
  ]
}```

edit : oh, nevermind i found your Pull Request :+1:

**Comment by inorganik** [comment]
The schematic actually removes that file, so it should probably update tsconfig.spec.json as well.

**Comment by zoltan-nz** [comment]
This repo's `yarn test` is actually failing, so the repo's test harness is right. ;)
Travis Test: https://travis-ci.com/zoltan-nz/jest-schematic

Sorry, I just now realised, that @dimpu already opened a pull request for fixing this issue... meanwhile I also worked on a fix... anyway, hope this problem can be solved soon...
